export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOGOUT_RECIEVED = 'LOGOUT_RECIEVED';
export const USER_ERROR = 'USER_ERROR';
export const USER_ERROR_CLR = 'USER_ERROR_CLR'
export const USER_LOADED = 'USER_LOADED';
export const FETCH_NAME = 'FETCH_NAME';
export const FETCH_COLOR = 'FETCH_COLOR';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_NEXT_POSTS = 'FETCH_NEXT_POSTS';
export const RECIEVE_POSTS = 'RECIEVE_POSTS';
export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POST';
export const RECIEVE_SINGLE_POST = 'RECIEVE_SINGLE_POST'

